In [1]:
from sportsreference.mlb.boxscore import Boxscore

game_data = Boxscore('BOS/BOS201808020')
print(game_data.home_runs)
print(game_data.away_runs)
df = game_data.dataframe

15
7

In [2]:
df.head()

,date,time,venue,attendance,duration,time_of_day,winner,winning_name,winning_abbr,losing_name,...,home_strikes_looking,home_grounded_balls,home_fly_balls,home_line_drives,home_unknown_bat_type,home_game_score,home_inherited_runners,home_inherited_score,home_win_probability_by_pitcher,home_base_out_runs_saved
BOS/BOS201808020,"Thursday, August 2, 2018",7:10 p.m. Local,Fenway Park,37317,3:25,Night,Home,Boston Red Sox,BOS,New York Yankees,...,28,12,28,13,0,46,0,0,-0.179,-2.2

In [3]:
from sportsreference.mlb.schedule import Schedule

houston_schedule = Schedule('HOU')
i = 5
for game in houston_schedule:
    print(game.date)
    print(game.result)
    for player in game.boxscore.away_players:
        print(player.name)
    if i == 0:
        break
    i -= 1

Friday, Jul 24
Win
Shed Long
Evan White
Kyle Seager
Kyle Lewis
Daniel Vogelbach
Austin Nola
Jose Marmolejos
J.P. Crawford
Mallex Smith
Tim Lopes
Marco Gonzales
Zac Grotz
Anthony Misiewicz
Carl Edwards Jr.
Yohan Ramirez
Saturday, Jul 25
Win
Shed Long
Evan White
Kyle Seager
Kyle Lewis
Austin Nola
Daniel Vogelbach
Dee Strange-Gordon
J.P. Crawford
Mallex Smith
Taijuan Walker
Brandon Brennan
Nestor Cortes Jr.
Bryan Shaw
Taylor Williams
Sunday, Jul 26
Loss
Shed Long
J.P. Crawford
Kyle Lewis
Kyle Seager
Evan White
Jose Marmolejos
Tim Lopes
Mallex Smith
Joe Hudson
Austin Nola
Yusei Kikuchi
Zac Grotz
Matt Magill
Carl Edwards Jr.
Dan Altavilla
Anthony Misiewicz
Taylor Williams
Monday, Jul 27
Win
Shed Long
J.P. Crawford
Kyle Lewis
Kyle Seager
Evan White
Jose Marmolejos
Austin Nola
Tim Lopes
Dee Strange-Gordon
Kendall Graveman
Taylor Guilbeau
Yohan Ramirez
Nick Margevicius
Tuesday, Jul 28
Loss
Mookie Betts
Max Muncy
Justin Turner
Cody Bellinger
Chris Taylor
Corey Seager
AJ Pollock
Enrique Hernandez
Will Smith
Walker Buehler
Adam Kolarek
Brusdar Graterol
Joe Kelly
Caleb Ferguson
Blake Treinen
Kenley Jansen
Wednesday, Jul 29
Loss
Max Muncy
Mookie Betts
Cody Bellinger
Justin Turner
Corey Seager
Chris Taylor
Joc Pederson
Enrique Hernandez
Matt Beaty
AJ Pollock
Terrance Gore
Edwin Rios
Austin Barnes
Dustin May
Jake McGee
Dylan Floro
Pedro Baez
Caleb Ferguson
Blake Treinen
Kenley Jansen
Scott Alexander
Dennis Santana

In [4]:
hou_schedule = Schedule('HOU')

game = hou_schedule[0]
date = game.datetime
print(date)
print(game.day_or_night)

player = game.boxscore.home_players[0]
print(player.name, "(BIG UConn guy)")
print("hits:", player.hits)
print("at bats:", player.at_bats)
print("plate appearances:", player.plate_appearances)
print("strikeouts:", player.times_struck_out)
print("batting average:", player.batting_average)
print("RBI:", player.runs_batted_in)
print("runs scored:", player.runs)

2020-07-24 00:00:00
Night
George Springer (BIG UConn guy)
hits: 0
at bats: 3
plate appearances: 5
strikeouts: 1
batting average: 0.0
RBI: 0
runs scored: 0

In [5]:
import pandas as pd

games_data = pd.DataFrame()

len(games_data)

0

# Get Teams from 2014 to 2019

create a dictionary where the keys are the years (2014 - 2019) and the values are a lists of teams,

In [6]:
from sportsreference.mlb.teams import Teams

years = [2014, 2015, 2016, 2017, 2018, 2019]

MLB_teams_from_ = dict()
for yr in years:
    MLB_teams_from_[yr] = Teams(year=yr)

# Get one specific team
## in this case, we choose houston

We do this as an example, we will expand this to include all teams over the years from 2014 to 2019, but this is a good starting point for now

In [7]:
mets = MLB_teams_from_[2015]['NYM']

# Get Mets' schedule for the 2015 season

In [8]:
mets_schedule = mets.schedule

# Get the boxscores for each game from that season
### This will take quite a while to complete so don't fret if it doesn't finish right away (is there a way to speed tihs up? Does this suggest we should use Online Learning model instead of Batch? or maybe we just have super small batches. IDK, lmk what you think)

In [9]:
mets_boxscores = mets_schedule.dataframe_extended

mets_boxscores.head()

,date,time,venue,attendance,duration,time_of_day,winner,winning_name,winning_abbr,losing_name,...,home_strikes_looking,home_grounded_balls,home_fly_balls,home_line_drives,home_unknown_bat_type,home_game_score,home_inherited_runners,home_inherited_score,home_win_probability_by_pitcher,home_base_out_runs_saved
WAS/WAS201504060,"Monday, April 6, 2015",4:09 p.m. Local,Nationals Park,42295,2:35,Day,Away,New York Mets,NYM,Washington Nationals,...,25,15,6,2,0,71,4,0,-0.060,1.3
WAS/WAS201504080,"Wednesday, April 8, 2015",8:01 p.m. Local,Nationals Park,25999,2:21,Night,Home,Washington Nationals,WSN,New York Mets,...,20,10,13,6,0,62,0,0,0.630,3.3
WAS/WAS201504090,"Thursday, April 9, 2015",1:07 p.m. Local,Nationals Park,25327,2:54,Day,Away,New York Mets,NYM,Washington Nationals,...,25,10,12,6,0,34,2,0,-0.253,-1.7
ATL/ATL201504100,"Friday, April 10, 2015",8:51 p.m. Local,Turner Field,46279,3:01,Night,Home,Atlanta Braves,ATL,New York Mets,...,28,20,9,6,0,43,0,0,0.253,1.0
ATL/ATL201504110,"Saturday, April 11, 2015",7:14 p.m. Local,Turner Field,36056,2:25,Night,Home,Atlanta Braves,ATL,New York Mets,...,23,17,11,6,0,61,4,1,0.351,1.0

In [10]:
len(mets_boxscores) # verify that it is a full season

162

# Make a train and a test set
## haha whoops almost forgot this

In [11]:
from sklearn.model_selection import train_test_split

mets_boxscores, mets_test = train_test_split(mets_boxscores, test_size=0.2, random_state=42)

# Get rid of labels we don't care about
### This is mainly the categorical data, may need to tinker with this aspect (remove additional numerical features)!

In [12]:
# first let's get a sense of all the features we're dealing with

mets_boxscores.columns

Index(['date', 'time', 'venue', 'attendance', 'duration', 'time_of_day',
       'winner', 'winning_name', 'winning_abbr', 'losing_name', 'losing_abbr',
       'away_at_bats', 'away_runs', 'away_hits', 'away_rbi',
       'away_earned_runs', 'away_bases_on_balls', 'away_strikeouts',
       'away_plate_appearances', 'away_batting_average',
       'away_on_base_percentage', 'away_slugging_percentage',
       'away_on_base_plus', 'away_pitches', 'away_strikes',
       'away_win_probability_for_offensive_player',
       'away_average_leverage_index', 'away_win_probability_added',
       'away_win_probability_subtracted', 'away_base_out_runs_added',
       'away_putouts', 'away_assists', 'away_innings_pitched',
       'away_home_runs', 'away_strikes_by_contact', 'away_strikes_swinging',
       'away_strikes_looking', 'away_grounded_balls', 'away_fly_balls',
       'away_line_drives', 'away_unknown_bat_type', 'away_game_score',
       'away_inherited_runners', 'away_inherited_score',
       'away_win_probability_by_pitcher', 'away_base_out_runs_saved',
       'home_at_bats', 'home_runs', 'home_hits', 'home_rbi',
       'home_earned_runs', 'home_bases_on_balls', 'home_strikeouts',
       'home_plate_appearances', 'home_batting_average',
       'home_on_base_percentage', 'home_slugging_percentage',
       'home_on_base_plus', 'home_pitches', 'home_strikes',
       'home_win_probability_for_offensive_player',
       'home_average_leverage_index', 'home_win_probability_added',
       'home_win_probability_subtracted', 'home_base_out_runs_added',
       'home_putouts', 'home_assists', 'home_innings_pitched',
       'home_home_runs', 'home_strikes_by_contact', 'home_strikes_swinging',
       'home_strikes_looking', 'home_grounded_balls', 'home_fly_balls',
       'home_line_drives', 'home_unknown_bat_type', 'home_game_score',
       'home_inherited_runners', 'home_inherited_score',
       'home_win_probability_by_pitcher', 'home_base_out_runs_saved'],
      dtype='object')

In [46]:
# Keep only the 'winner' column - these will be our targets
## maybe make this into a function for easier pipelining - def do this!

def drop_cat(data):
    return data.drop(columns=['attendance', # maybe a factor?
                              'away_unknown_bat_type',
                              'away_inherited_runners',
                              'away_inherited_score',
                       'date',
                       'duration',
                        'home_unknown_bat_type',
                       'losing_abbr',
                       'losing_name',
                       'time',
                       'time_of_day',
                       'winning_abbr',
                       'winning_name',
                       'venue',
                       'winner'
                      ])
    
    
mets_boxscores_num = drop_cat(mets_boxscores)
mets_test_num = drop_cat(mets_test)

In [47]:
mets_boxscores_num.shape

(129, 66)

In [48]:
mets_boxscores_num.head()

,away_at_bats,away_runs,away_hits,away_rbi,away_earned_runs,away_bases_on_balls,away_strikeouts,away_plate_appearances,away_batting_average,away_on_base_percentage,...,home_strikes_swinging,home_strikes_looking,home_grounded_balls,home_fly_balls,home_line_drives,home_game_score,home_inherited_runners,home_inherited_score,home_win_probability_by_pitcher,home_base_out_runs_saved
NYN/NYN201509230,33,6,9,6,6.0,3,4,38,0.273,0.351,...,9,28,11,19,12,51,3,3,-0.541,-2.0
WAS/WAS201504090,36,6,10,6,3.0,3,9,40,0.278,0.350,...,16,25,10,12,6,34,2,0,-0.253,-1.7
PHI/PHI201508250,34,6,7,6,5.0,6,10,40,0.206,0.325,...,23,32,8,11,6,43,4,2,-0.382,-2.0
NYN/NYN201505250,33,3,6,3,3.0,3,10,37,0.182,0.243,...,16,22,7,14,7,52,1,0,0.045,1.0
PIT/PIT201505220,28,1,6,0,0.0,1,10,31,0.214,0.267,...,11,24,14,10,4,78,2,0,0.361,3.1

In [49]:
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

## DROP COLUMNS THAT HAVE MISSING VALUES
mets_boxscores_num_dropna = mets_boxscores_num.dropna(axis=1)
mets_test_num_dropna = mets_test_num.dropna(axis=1)

std_scaler = StandardScaler()
imputer = SimpleImputer()
## ADD AN IMPUTER TO MAKE SURE ALL DATA HAS VALUES

mets_boxscores_num_imputed = imputer.fit_transform(mets_boxscores_num_dropna)
mets_test_num_imputed = imputer.fit_transform(mets_test_num_dropna)

mets_boxscores_num_scaled = std_scaler.fit_transform(mets_boxscores_num_imputed)
mets_test_num_scaled = std_scaler.fit_transform(mets_test_num_imputed)

mets_boxscores_num_scaled = pd.DataFrame(mets_boxscores_num_scaled,
                                         index=mets_boxscores_num.index,
                                         columns=mets_boxscores_num.columns)
mets_test_num_scaled = pd.DataFrame(mets_test_num_scaled,
                                    index=mets_test_num.index,
                                    columns=mets_test_num.columns)

#mets_boxscores_num_imputed.head()
mets_boxscores_num_scaled.head()

,away_at_bats,away_runs,away_hits,away_rbi,away_earned_runs,away_bases_on_balls,away_strikeouts,away_plate_appearances,away_batting_average,away_on_base_percentage,...,home_strikes_swinging,home_strikes_looking,home_grounded_balls,home_fly_balls,home_line_drives,home_game_score,home_inherited_runners,home_inherited_score,home_win_probability_by_pitcher,home_base_out_runs_saved
NYN/NYN201509230,-0.384302,0.620565,0.137062,0.682986,0.805674,0.152176,-1.321066,-0.090830,0.488829,0.728502,...,-0.900647,0.642857,-0.275694,1.299970,1.920511,-0.242824,0.789460,2.637636,-1.595069,-0.685566
WAS/WAS201504090,0.189925,0.620565,0.422240,0.682986,-0.200086,0.152176,0.179088,0.217514,0.557193,0.715486,...,0.473144,0.113526,-0.553543,-0.457325,-0.212165,-1.165724,0.238972,-0.522628,-0.817389,-0.591249
PHI/PHI201508250,-0.192893,0.620565,-0.433293,0.682986,0.470420,1.624479,0.479119,0.217514,-0.427248,0.390082,...,1.846935,1.348632,-1.109239,-0.708367,-0.212165,-0.677130,1.339949,1.584215,-1.165725,-0.685566
NYN/NYN201505250,-0.384302,-0.321233,-0.718471,-0.278162,-0.200086,0.152176,0.479119,-0.245002,-0.755395,-0.677245,...,0.473144,-0.415805,-1.387087,0.044759,0.143281,-0.188536,-0.311517,-0.522628,-0.012706,0.257605
PIT/PIT201505220,-1.341347,-0.949099,-0.718471,-1.239309,-1.205846,-0.829359,0.479119,-1.170035,-0.317866,-0.364856,...,-0.508135,-0.062918,0.557850,-0.959409,-0.923058,1.222958,0.238972,-0.522628,0.840582,0.917825

In [58]:
mets_boxscores_cat = mets_boxscores['winner'].to_numpy() # returns a Pandas Series object
mets_test_cat = mets_test['winner'].to_numpy()

In [59]:
type(mets_boxscores_cat)

numpy.ndarray

In [65]:
from sklearn.svm import SVC

svm_clf = SVC(kernel="poly", degree=3, coef0=1, C=5)

svm_clf.fit(mets_boxscores_num_scaled, mets_boxscores_cat)

SVC(C=5, coef0=1, kernel='poly')

In [69]:
mets_boxscores_predictions = svm_clf.predict(mets_test_num_scaled)

In [70]:
mets_boxscores_predictions

array(['Home', 'Home', 'Away', 'Home', 'Home', 'Away', 'Away', 'Away',
       'Away', 'Away', 'Away', 'Home', 'Home', 'Home', 'Away', 'Away',
       'Home', 'Home', 'Home', 'Home', 'Home', 'Home', 'Home', 'Home',
       'Home', 'Away', 'Home', 'Home', 'Home', 'Away', 'Away', 'Away',
       'Home'], dtype=object)

In [71]:
mets_test_cat

array(['Home', 'Home', 'Away', 'Home', 'Home', 'Away', 'Away', 'Away',
       'Away', 'Away', 'Away', 'Home', 'Home', 'Home', 'Away', 'Away',
       'Home', 'Home', 'Home', 'Home', 'Home', 'Home', 'Home', 'Home',
       'Home', 'Away', 'Home', 'Home', 'Home', 'Away', 'Away', 'Away',
       'Home'], dtype=object)

# Starting to use RetroSheet data
## much quicker so far

In [78]:
baseball_games_2015 = pd.read_csv('../datasets/retro_sheet_gls/GL2015.TXT')

In [79]:
baseball_games_2015.head()

,Date,Number of game,Day,Visiting Team,Visiting Team League,Visiting Team Game Number,Home Team,Home Team League,Home Team Game Number,Visiting Team Score,...,Home Team Player 7 Name,Home Team Player 7 Defensive Position,Home Team Player 8 ID,Home Team Player 8 Name,Home Team Player 8 Defensive Position,Home Team Player 9 ID,Home Team Player 9 Name,Home Team Player 9 Defensive Position,Miscellaneous,Acquisition Information
0,20150405,0,Sun,SLN,NL,1,CHN,NL,1,3,...,David Ross,2,lestj001,Jon Lester,1,lastt001,Tommy La Stella,4,NaN,Y
1,20150406,0,Mon,MIN,AL,1,DET,AL,1,0,...,Nick Castellanos,5,avila001,Alex Avila,2,iglej001,Jose Iglesias,6,NaN,Y
2,20150406,0,Mon,CLE,AL,1,HOU,AL,1,0,...,Jed Lowrie,6,rasmc001,Colby Rasmus,7,marij002,Jake Marisnick,8,NaN,Y
3,20150406,0,Mon,CHA,AL,1,KCA,AL,1,1,...,Alex Rios,9,peres002,Salvador Perez,2,infao001,Omar Infante,4,NaN,Y
4,20150406,0,Mon,TOR,AL,1,NYA,AL,1,6,...,Alex Rodriguez,10,drews001,Stephen Drew,4,gregd001,Didi Gregorius,6,NaN,Y

In [80]:
baseball_games_2015.shape

(2429, 161)

In [90]:
baseball_games_2015_NL.shape

(1065, 161)

In [112]:
baseball_games_2015_NL = baseball_games_2015[(baseball_games_2015['Visiting Team League'] == 'NL')
                                            &
                                            (baseball_games_2015['Home Team League'] == 'NL')]

In [113]:
baseball_games_2015_NL.head()

,Date,Number of game,Day,Visiting Team,Visiting Team League,Visiting Team Game Number,Home Team,Home Team League,Home Team Game Number,Visiting Team Score,...,Home Team Player 7 Name,Home Team Player 7 Defensive Position,Home Team Player 8 ID,Home Team Player 8 Name,Home Team Player 8 Defensive Position,Home Team Player 9 ID,Home Team Player 9 Name,Home Team Player 9 Defensive Position,Miscellaneous,Acquisition Information
0,20150405,0,Sun,SLN,NL,1,CHN,NL,1,3,...,David Ross,2,lestj001,Jon Lester,1,lastt001,Tommy La Stella,4,NaN,Y
8,20150406,0,Mon,SFN,NL,1,ARI,NL,1,5,...,Tuffy Gosewisch,2,ahmen001,Nick Ahmed,6,collj001,Josh Collmenter,1,NaN,Y
9,20150406,0,Mon,PIT,NL,1,CIN,NL,1,2,...,Brandon Phillips,4,cozaz001,Zack Cozart,6,cuetj001,Johnny Cueto,1,NaN,Y
10,20150406,0,Mon,SDN,NL,1,LAN,NL,1,3,...,Joc Pederson,8,ellia001,A.J. Ellis,2,kersc001,Clayton Kershaw,1,NaN,Y
11,20150406,0,Mon,ATL,NL,1,MIA,NL,1,2,...,Jarrod Saltalamacchia,2,hecha001,Adeiny Hechavarria,6,alvah001,Henderson Alvarez,1,NaN,Y

In [115]:
baseball_games_2015_NL.shape

(1065, 161)

In [120]:
baseball_games_2015_NL.loc[300, 'Home Team Game Number']

20

In [125]:
# get the team team_abrv boxscores from data

def get_team(data, team_abrv):
    return data[(data['Visiting Team'] == team_abrv) | (data['Home Team'] == team_abrv)]

In [130]:
pit_2015 = get_team(baseball_games_2015, team_abrv='PIT')

In [135]:
pit_2015.reset_index(inplace=True)
pit_2015.head()

,index,Date,Number of game,Day,Visiting Team,Visiting Team League,Visiting Team Game Number,Home Team,Home Team League,Home Team Game Number,...,Home Team Player 7 Name,Home Team Player 7 Defensive Position,Home Team Player 8 ID,Home Team Player 8 Name,Home Team Player 8 Defensive Position,Home Team Player 9 ID,Home Team Player 9 Name,Home Team Player 9 Defensive Position,Miscellaneous,Acquisition Information
0,9,20150406,0,Mon,PIT,NL,1,CIN,NL,1,...,Brandon Phillips,4,cozaz001,Zack Cozart,6,cuetj001,Johnny Cueto,1,NaN,Y
1,31,20150408,0,Wed,PIT,NL,2,CIN,NL,2,...,Brandon Phillips,4,cozaz001,Zack Cozart,6,leakm001,Mike Leake,1,NaN,Y
2,42,20150409,0,Thu,PIT,NL,3,CIN,NL,3,...,Brandon Phillips,4,cozaz001,Zack Cozart,6,desca001,Anthony DeSclafani,1,NaN,Y
3,58,20150410,0,Fri,PIT,NL,4,MIL,NL,4,...,Jean Segura,6,genns001,Scooter Gennett,4,fierm001,Michael Fiers,1,NaN,Y
4,73,20150411,0,Sat,PIT,NL,5,MIL,NL,5,...,Jean Segura,6,gomeh001,Hector Gomez,4,nelsj004,Jimmy Nelson,1,NaN,Y

In [136]:
# This ~should~ result in 162 total games

pit_2015.shape

(162, 162)

In [183]:
# get pertinent stats from the previous 20 games
## game_i corresponds to the i-th most recent game

def get_previous_game(team_data, current_game_number):
    previous_game_number = current_game_number - 1 # start with values over 20
    return team_data.loc[previous_game_number, ]

def get_previous_20_games(team_data, current_game_number):
    previous_20 = pd.DataFrame()
    n = 20
    while n > 0:
        previous_20 = pd.concat([previous_20, 
                                 get_previous_game(team_data, current_game_number-n)],
                               axis=1)
        n -= 1
    
    return previous_20.T.reset_index()

In [184]:
pit_previous_20 = get_previous_20_games(pit_2015, 100)

In [185]:
pit_previous_20.shape

(20, 163)

In [186]:
pit_previous_20.head(20)

,level_0,index,Date,Number of game,Day,Visiting Team,Visiting Team League,Visiting Team Game Number,Home Team,Home Team League,...,Home Team Player 7 Name,Home Team Player 7 Defensive Position,Home Team Player 8 ID,Home Team Player 8 Name,Home Team Player 8 Defensive Position,Home Team Player 9 ID,Home Team Player 9 Name,Home Team Player 9 Defensive Position,Miscellaneous,Acquisition Information
0,79,1216,20150704,0,Sat,CLE,AL,80,PIT,NL,...,Gregory Polanco,9,mercj002,Jordy Mercer,6,lockj001,Jeff Locke,1,NaN,Y
1,80,1231,20150705,0,Sun,CLE,AL,81,PIT,NL,...,Jordy Mercer,6,stewc001,Chris Stewart,2,coleg001,Gerrit Cole,1,NaN,Y
2,81,1241,20150706,0,Mon,SDN,NL,85,PIT,NL,...,Jordy Mercer,6,rodrs002,Sean Rodriguez,7,burna001,A.J. Burnett,1,NaN,Y
3,82,1258,20150707,0,Tue,SDN,NL,86,PIT,NL,...,Sean Rodriguez,7,stewc001,Chris Stewart,2,lirif001,Francisco Liriano,1,NaN,Y
4,83,1273,20150708,0,Wed,SDN,NL,87,PIT,NL,...,Jordy Mercer,6,rodrs002,Sean Rodriguez,7,mortc002,Charlie Morton,1,NaN,Y
5,84,1284,20150709,0,Thu,SLN,NL,86,PIT,NL,...,Jordy Mercer,6,rodrs002,Sean Rodriguez,7,lockj001,Jeff Locke,1,NaN,Y
6,85,1298,20150710,0,Fri,SLN,NL,87,PIT,NL,...,Travis Ishikawa,7,stewc001,Chris Stewart,2,coleg001,Gerrit Cole,1,NaN,Y
7,86,1313,20150711,0,Sat,SLN,NL,88,PIT,NL,...,Francisco Cervelli,2,mercj002,Jordy Mercer,6,burna001,A.J. Burnett,1,NaN,Y
8,87,1328,20150712,0,Sun,SLN,NL,89,PIT,NL,...,Sean Rodriguez,3,polag001,Gregory Polanco,9,lirif001,Francisco Liriano,1,NaN,Y
9,88,1341,20150717,0,Fri,PIT,NL,89,MIL,NL,...,Jean Segura,6,genns001,Scooter Gennett,4,fierm001,Michael Fiers,1,NaN,Y
10,89,1356,20150718,0,Sat,PIT,NL,90,MIL,NL,...,Jean Segura,6,maldm001,Martin Maldonado,2,nelsj004,Jimmy Nelson,1,NaN,Y
11,90,1370,20150719,0,Sun,PIT,NL,91,MIL,NL,...,Khris Davis,7,pereh001,Hernan Perez,4,jungt001,Taylor Jungmann,1,NaN,Y
12,91,1377,20150720,0,Mon,PIT,NL,92,KCA,AL,...,Omar Infante,4,riosa002,Alex Rios,9,dysoj001,Jarrod Dyson,7,NaN,Y
13,92,1389,20150721,0,Tue,PIT,NL,93,KCA,AL,...,Omar Infante,4,riosa002,Alex Rios,9,dysoj001,Jarrod Dyson,7,NaN,Y
14,93,1404,20150722,0,Wed,PIT,NL,94,KCA,AL,...,Omar Infante,4,riosa002,Alex Rios,9,dysoj001,Jarrod Dyson,7,NaN,Y
15,94,1424,20150723,0,Thu,WAS,NL,94,PIT,NL,...,Francisco Cervelli,2,moreb001,Brent Morel,5,lirif001,Francisco Liriano,1,NaN,Y
16,95,1438,20150724,0,Fri,WAS,NL,95,PIT,NL,...,Francisco Cervelli,2,florp001,Pedro Florimon,6,lockj001,Jeff Locke,1,NaN,Y
17,96,1453,20150725,0,Sat,WAS,NL,96,PIT,NL,...,Neil Walker,4,rodrs002,Sean Rodriguez,3,burna001,A.J. Burnett,1,NaN,Y
18,97,1468,20150726,0,Sun,WAS,NL,97,PIT,NL,...,Pedro Alvarez,3,stewc001,Chris Stewart,2,coleg001,Gerrit Cole,1,NaN,Y
19,98,1485,20150728,0,Tue,PIT,NL,99,MIN,AL,...,Aaron Hicks,8,suzuk001,Kurt Suzuki,2,escoe001,Eduardo Escobar,6,NaN,Y

In [212]:
pit_previous_boxscore = Boxscore(str(pit_previous_20.loc[19,'Home Team'])
                                 + '//'
                                 + str(pit_previous_20.loc[19,'Home Team'])
                                 + str(pit_previous_20.loc[19,'Date'])
                                 + str(pit_previous_20.loc[19,'Number of game']))

In [213]:
pit_previous_players = pit_previous_boxscore.away_players

In [216]:
for player in pit_previous_players:
    print(player.name)

Gregory Polanco
Neil Walker
Andrew McCutchen
Aramis Ramirez
Jung Ho Kang
Pedro Alvarez
Francisco Cervelli
Travis Ishikawa
Sean Rodriguez
Jaff Decker
Charlie Morton
Jared Hughes
Tony Watson
Mark Melancon

In [219]:
pit_starting_players = [pit_previous_20.loc[19, 'Visiting Team Player ' + str(i+1) + ' Name'] for i in range(9)]
mil_starting_players = [pit_previous_20.loc[19, 'Home Team Player ' + str(i+1) + ' Name'] for i in range(9)]

In [221]:
for player in pit_starting_players:
    print(player)

Gregory Polanco
Neil Walker
Andrew McCutchen
Aramis Ramirez
Jung Ho Kang
Pedro Alvarez
Francisco Cervelli
Travis Ishikawa
Jaff Decker

In [223]:
team_starters_hits = 0
team_starters_at_bats = 0
for player in pit_previous_players:
    if player.name in pit_starting_players:
        team_starters_hits += player.hits
        team_starters_at_bats += player.at_bats
        
team_starters_batting_avg = team_starters_hits / team_starters_at_bats

In [224]:
print(team_starters_batting_avg)
print(pit_previous_20.loc[19, 'Visiting Team Hits'] / pit_previous_20.loc[19, 'Visiting Team At-bats'])

0.2972972972972973
0.28205128205128205